import React from 'react';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { ReportAnalysis } from '@/lib/ai/sentiment';

// 创建 PDF 文档组件
interface ReportPDFProps {
  report: {
    subreddit: string;
    pmf_score: number;
    total_posts: number;
    avg_sentiment: number;
    created_at: string;
  };
  analysis: ReportAnalysis;
  topPosts: Array<{
    title: string;
    score: number;
    sentiment: string;
    url: string;
  }>;
}

const ReportPDFDocument: React.FC<ReportPDFProps> = ({ report, analysis, topPosts }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* 标题 */}
      <View style={styles.header}>
        <Text style={styles.title}>ReddigInsight 分析报告</Text>
        <Text style={styles.subtitle}>r/{report.subreddit}</Text>
        <Text style={styles.date}>生成时间：{new Date(report.created_at).toLocaleDateString('zh-CN')}</Text>
      </View>

      {/* PMF 评分 */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>PMF 评分 (Product-Market Fit)</Text>
        <View style={styles.scoreContainer}>
          <Text style={styles.score}>{(report.pmf_score * 10).toFixed(1)}</Text>
          <Text style={styles.scoreLabel}>/ 10</Text>
        </View>
      </View>

      {/* 数据概览 */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>数据概览</Text>
        <View style={styles.statsGrid}>
          <View style={styles.statItem}>
            <Text style={styles.statValue}>{report.total_posts}</Text>
            <Text style={styles.statLabel}>分析帖子数</Text>
          </View>
          <View style={styles.statItem}>
            <Text style={styles.statValue}>{(report.avg_sentiment * 100).toFixed(0)}%</Text>
            <Text style={styles.statLabel}>平均情感分</Text>
          </View>
          <View style={styles.statItem}>
            <Text style={styles.statValue}>{analysis.positiveInsights.length}</Text>
            <Text style={styles.statLabel}>正面洞察</Text>
          </View>
          <View style={styles.statItem}>
            <Text style={styles.statValue}>{analysis.negativeInsights.length}</Text>
            <Text style={styles.statLabel}>负面洞察</Text>
          </View>
        </View>
      </View>

      {/* 正面洞察 */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>正面洞察</Text>
        {analysis.positiveInsights.map((insight, index) => (
          <View key={index} style={styles.insightItem}>
            <Text style={styles.insightText}>• {insight}</Text>
          </View>
        ))}
      </View>

      {/* 负面洞察 */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>负面洞察</Text>
        {analysis.negativeInsights.map((insight, index) => (
          <View key={index} style={styles.insightItem}>
            <Text style={styles.insightText}>• {insight}</Text>
          </View>
        ))}
      </View>

      {/* 热门帖子 */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>热门帖子分析</Text>
        {topPosts.map((post, index) => (
          <View key={index} style={styles.postItem}>
            <Text style={styles.postTitle}>{post.title}</Text>
            <View style={styles.postMeta}>
              <Text style={styles.postScore}>👍 {post.score}</Text>
              <Text style={styles.postSentiment}>情感：{post.sentiment}</Text>
            </View>
            <Text style={styles.postUrl} break>{post.url}</Text>
          </View>
        ))}
      </View>

      {/* 页脚 */}
      <View style={styles.footer}>
        <Text style={styles.footerText}>Generated by ReddigInsight - AI-Powered Reddit Analytics</Text>
      </View>
    </Page>
  </Document>
);

// 样式定义
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: 2,
    borderColor: '#000',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 18,
    color: '#666',
    marginBottom: 5,
  },
  date: {
    fontSize: 10,
    color: '#999',
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#333',
  },
  scoreContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    backgroundColor: '#f0f0f0',
    padding: 15,
    borderRadius: 8,
  },
  score: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#4CAF50',
  },
  scoreLabel: {
    fontSize: 14,
    color: '#666',
    marginLeft: 5,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  statItem: {
    width: '25%',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#f5f5f5',
    borderRadius: 5,
    margin: 5,
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2196F3',
  },
  statLabel: {
    fontSize: 8,
    color: '#666',
    marginTop: 3,
    textAlign: 'center',
  },
  insightItem: {
    marginBottom: 5,
    paddingLeft: 10,
  },
  insightText: {
    fontSize: 10,
    lineHeight: 1.4,
  },
  postItem: {
    marginBottom: 10,
    padding: 8,
    backgroundColor: '#f9f9f9',
    borderRadius: 5,
  },
  postTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  postMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  postScore: {
    fontSize: 9,
    color: '#FF9800',
  },
  postSentiment: {
    fontSize: 9,
    color: '#666',
  },
  postUrl: {
    fontSize: 8,
    color: '#2196F3',
    textDecoration: 'underline',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    borderTop: 1,
    borderColor: '#ddd',
    paddingTop: 10,
    textAlign: 'center',
  },
  footerText: {
    fontSize: 8,
    color: '#999',
    textAlign: 'center',
  },
});

// 导出函数
export async function generateReportPDF(
  report: ReportPDFProps['report'],
  analysis: ReportAnalysis,
  topPosts: ReportPDFProps['topPosts']
): Promise<Blob> {
  const doc = (
    <ReportPDFDocument 
      report={report} 
      analysis={analysis} 
      topPosts={topPosts} 
    />
  );
  
  const blob = await pdf(doc).toBlob();
  return blob;
}
