import { NextRequest, NextResponse } from 'next/server';
export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: reportId } = await params;
  try {
    const authHeader = request.headers.get('Authorization');
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'Authorization required' }, { status: 401 });
    }
    const token = authHeader.slice(7);
    const backendUrl = process.env.BACKEND_URL || 'http://106.15.90.140:13001';
    const resp = await fetch(backendUrl + '/api/reports/' + reportId, {
      headers: { Authorization: 'Bearer ' + token },
    });
    if (!resp.ok) {
      return NextResponse.json({ error: 'Failed to fetch report' }, { status: resp.status });
    }
    const payload = await resp.json();
    const r = payload.report;
    if (!r) return NextResponse.json({ error: 'Report not found' }, { status: 404 });

    const sub = r.metadata?.subreddit || r.subreddit || 'unknown';
    const total = r.totalCount ?? r.total_posts ?? 0;
    const pmf = r.pmfScore ?? r.pmf_score ?? 0;
    const avgSent = r.avgSentimentScore ?? r.avg_sentiment_score ?? 0;
    const pos = r.positiveSentimentCount ?? 0;
    const neg = r.negativeSentimentCount ?? 0;
    const neu = r.neutralSentimentCount ?? (total - pos - neg);
    const topPosts = (r.topPosts || r.top_posts || []).slice(0, 10);
    const disc = r.discussionSummary || r.discussion_summary || [];
    const quotes = r.keyQuotes || r.key_quotes || [];
    const recs = r.actionRecommendations || r.action_recommendations || [];
    const kw = r.metadata?.keywords || r.topKeywords || r.top_keywords || r.keyTopics || [];
    const inf = r.avgInfluenceScore ?? r.avg_influence_score;
    const createdAt = r.metadata?.createdAt || r.created_at;

    const fd = (dt: any) => { if (!dt) return 'N/A'; try { var d = typeof dt === 'number' ? new Date(dt * 1000) : new Date(dt); return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }); } catch { return 'N/A'; } };
    const esc = (s: string) => (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    var pct = function(n: number) { return total > 0 ? ((n / total) * 100).toFixed(0) : '0'; };
    var negPct = pct(neg), neuPct = pct(neu), posPct = pct(pos);
    var avgDisp = typeof avgSent === 'number' ? (avgSent * 100).toFixed(0) + '%' : String(avgSent);
    var infDisp = inf != null ? (typeof inf === 'number' ? inf.toFixed(1) + ' / 10' : String(inf)) : null;
    var ac = { reply: 'blue', suggest: 'blue', ignore: 'gray', moderate: 'yellow', escalate: 'red' };

    var css = 'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;max-width:900px;margin:0 auto;padding:20px;color:#1f2937;line-height:1.6}';
    css += 'h1{font-size:24px;margin:0}h2{font-size:18px;border-bottom:2px solid #e5e7eb;padding-bottom:8px;margin:24px 0 12px}';
    css += '.hdr{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px;margin-bottom:24px}';
    css += '.badge{display:inline-block;padding:2px 8px;border-radius:12px;font-size:12px;font-weight:600;margin:2px}';
    css += '.bg{background:#dcfce7;color:#16a34a}.br{background:#fee2e2;color:#dc2626}.bgy{background:#f3f4f6;color:#6b7280}.bb{background:#dbeafe;color:#2563eb}';
    css += '.card{border:1px solid #e5e7eb;border-radius:8px;padding:16px}.ct{font-size:13px;color:#6b7280;margin:0 0 4px}.cv{font-size:24px;font-weight:700;margin:0}';
    css += '.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:12px;margin-bottom:20px}';
    css += '.bar{height:16px;background:#e5e7eb;border-radius:8px;overflow:hidden;display:flex;margin:8px 0}';
    css += '.quote{border-left:4px solid #3b82f6;padding:8px 16px;margin:8px 0;background:#f9fafb}';
    css += '.rec{border:1px solid #e5e7eb;border-radius:8px;padding:12px;margin:8px 0}';
    css += 'table{width:100%;border-collapse:collapse;margin:12px 0}th,td{text-align:left;padding:8px 12px;border-bottom:1px solid #e5e7eb}th{font-size:13px;color:#6b7280;font-weight:600}td{font-size:14px}';
    css += 'a{color:#2563eb;text-decoration:none}.footer{margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;text-align:center}';

    var body = '<div class="hdr">\n<h1>ReddigInsight Report: r/' + sub + '</h1>\n<span class="badge bb">Generated by AI on ' + fd(createdAt) + '</span>\n</div>\n';
    body += '<div class="grid">\n';
    body += '<div class="card"><p class="ct">PMF Score</p><p class="cv">' + pmf + '/10</p></div>\n';
    if (infDisp) body += '<div class="card"><p class="ct">Influence Score</p><p class="cv">' + infDisp + '</p></div>\n';
    body += '<div class="card"><p class="ct">Average Sentiment</p><p class="cv">' + avgDisp + '</p></div>\n';
    body += '<div class="card"><p class="ct">Total Posts Analyzed</p><p class="cv">' + total + '</p></div>\n';
    body += '</div>\n';

    body += '<h2>Sentiment Breakdown</h2>\n';
    body += '<div><span class="badge br">-' + neg + ' Negative</span> <span class="badge bgy">' + neu + ' Neutral</span> <span class="badge bg">+' + pos + ' Positive</span></div>\n';
    body += '<div class="bar"><div style="background:#dc2626;height:100%;width:' + negPct + '%"></div><div style="background:#9ca3af;height:100%;width:' + neuPct + '%"></div><div style="background:#16a34a;height:100%;width:' + posPct + '%"></div></div>\n';
    body += '<div style="display:flex;justify-content:space-between;font-size:12px;color:#6b7280"><span>Negative ' + negPct + '%</span><span>Neutral ' + neuPct + '%</span><span>Positive ' + posPct + '%</span></div>\n';

    if (kw.length > 0) {
      body += '<h2>Top Keywords</h2>\n<div>' + kw.slice(0, 10).map(function(k: string) { return '<span class="badge bgy">' + esc(k) + '</span>'; }).join(' ') + '</div>\n';
    }
    if (disc.length > 0) {
      body += '<h2>Discussion Summary</h2>\n<ul>' + disc.map(function(d: string) { return '<li>' + esc(d) + '</li>'; }).join('') + '</ul>\n';
    }
    if (quotes.length > 0) {
      body += '<h2>Key Quotes</h2>\n' + quotes.map(function(q: any) { return '<div class="quote"><strong>' + esc(q.author || 'Anonymous') + ':</strong><br>' + esc(q.text || q.quote || '') + '</div>'; }).join('') + '\n';
    }
    if (recs.length > 0) {
      body += '<h2>Action Recommendations</h2>\n<p style="font-size:13px;color:#6b7280;font-style:italic">Disclaimer: AI-generated suggestions for informational purposes only. ReddigInsight assumes no liability for actions taken based on these recommendations.</p>\n';
      body += recs.map(function(r: any) { var t = typeof r === 'string' ? r : (r.reason || r.text || r.action || ''); return '<div class="rec"><strong>' + esc(t) + '</strong></div>'; }).join('') + '\n';
    }

    body += '<h2>Top Posts</h2>\n<table><tr><th>#</th><th>Title</th><th>Upvotes</th><th>Comments</th></tr>\n';
    if (topPosts.length > 0) {
      body += topPosts.map(function(p: any, i: number) {
        var t = esc(p.title || 'Untitled');
        var u = p.url || p.postUrl || '';
        var sc = p.score || p.upvotes || p.upVotes || 0;
        var nc = p.comments_count || p.num_comments || p.numComments || p.commentsCount || 0;
        var ds = fd(p.postedAt || p.created_utc || p.createdUtc || p.createdAt);
        var titleCell = u ? '<a href="' + u + '" target="_blank">' + t + '</a>' : t;
        return '<tr><td>' + (i + 1) + '</td><td>' + titleCell + '<br><span style="font-size:11px;color:#9ca3af">' + ds + '</span></td><td>' + sc.toLocaleString() + '</td><td>' + nc + '</td></tr>';
      }).join('') + '\n';
    } else {
      body += '<tr><td colspan="4">No posts found</td></tr>';
    }
    body += '</table>\n';
    body += '<div class="footer">Generated by ReddigInsight &mdash; AI-powered Reddit community insights</div>\n';

    var html = '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<title>ReddigInsight Report - r/' + sub + '</title>\n<style>\n' + css + '\n</style>\n</head>\n<body>\n' + body + '\n</body>\n</html>';

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': 'attachment; filename="reddiginsight-' + sub + '-' + reportId + '.html"',
      },
    });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}