import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import {
  ArrowRight,
  BookOpen,
  CheckCircle2,
  ClipboardList,
  FileText,
  MessageSquare,
  Settings2,
} from 'lucide-react'
import { DashboardNav } from '@/components/DashboardNav'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { createPublicMetadata } from '@/lib/seo'

export const metadata: Metadata = createPublicMetadata({
  title: 'How to Use AI Reddit Analysis',
  description:
    'Learn how to use ReddigInsight step by step: refine a research question in AI chat, generate a subreddit analysis from the dashboard, and review or export the finished report.',
  path: '/how-to-use',
  keywords: [
    'how to use Reddit analysis',
    'AI subreddit research',
    'Reddit sentiment report',
    'Reddit market research workflow',
  ],
})

const steps = [
  {
    step: 'Step 1',
    title: 'Define your research in AI Chat',
    description:
      'Describe your product idea, market, customer question, or research topic. The AI assistant helps turn that context into search inputs for Reddit research, including a subreddit, keywords, time range, and post limit.',
    bullets: [
      'Ask follow-up questions until the research goal is clear',
      'Review AI-suggested subreddits and keywords',
      'Select a time range and post limit for the analysis',
      'Send the confirmed parameters to the Dashboard',
    ],
    icon: MessageSquare,
    image: '/images/guide/chat.png',
    imageWidth: 1126,
    imageHeight: 960,
    imageAlt: 'The ReddigInsight AI chat interface with a research conversation and generated search parameters.',
    imageCaption: 'Chat helps you turn a research question into searchable Reddit parameters.',
  },
  {
    step: 'Step 2',
    title: 'Start the analysis from the Dashboard',
    description:
      'Open the Dashboard to review or edit the subreddit, keywords, time range, and maximum post count. When the parameters look right, start the analysis. One completed report uses one credit.',
    bullets: [
      'Use inputs generated by AI Chat or enter them directly',
      'Analyze public subreddit discussions related to your keywords',
      'Free accounts can analyze up to 100 posts per report',
      'Starter and Pro accounts can analyze up to 300 posts per report',
    ],
    icon: ClipboardList,
    image: '/images/guide/dashboard.png',
    imageWidth: 780,
    imageHeight: 1045,
    imageAlt: 'The ReddigInsight analysis dashboard with subreddit and keyword input controls.',
    imageCaption: 'Review the search parameters before you spend a credit.',
    tall: true,
  },
  {
    step: 'Step 3',
    title: 'Read and export your report',
    description:
      'Go to Reports to track progress and open the finished analysis. Reports organize community signals into sections you can scan quickly and share with collaborators.',
    bullets: [
      'Discussion summary and community sentiment',
      'Key themes, keywords, and representative quotes',
      'Product-market-fit and influence indicators',
      'Practical action recommendations and HTML export',
    ],
    icon: FileText,
    image: '/images/guide/report-detail.png',
    imageWidth: 780,
    imageHeight: 1978,
    imageAlt: 'A ReddigInsight subreddit analysis report with summary sections and insights.',
    imageCaption: 'Finished reports are stored in your account and can be exported as HTML.',
    tall: true,
  },
]

export default function HowToUsePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 dark:from-gray-900 dark:via-indigo-900/20 dark:to-purple-900/20">
      <DashboardNav />

      <section className="py-16 sm:py-20">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <Badge variant="secondary" className="mb-6 rounded-full bg-white/80 px-4 py-2 shadow-lg backdrop-blur-sm">
              <BookOpen className="mr-2 h-4 w-4 text-indigo-600" aria-hidden="true" />
              ReddigInsight Workflow
            </Badge>
            <h1 className="text-4xl font-bold leading-tight sm:text-5xl">
              How to Use ReddigInsight for Reddit Research
            </h1>
            <p className="mt-6 text-lg leading-relaxed text-muted-foreground">
              ReddigInsight turns public Reddit discussions into structured research reports. Use AI to clarify your
              question, define the subreddit search, generate a report, and export the findings for your team.
            </p>
            <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
              <Link href="/signup">
                <Button size="lg" className="gap-2 bg-gradient-to-r from-indigo-600 to-purple-600 text-white">
                  Create Free Account
                  <ArrowRight className="h-4 w-4" aria-hidden="true" />
                </Button>
              </Link>
              <Link href="/pricing">
                <Button size="lg" variant="outline">
                  View Pricing
                </Button>
              </Link>
            </div>
            <p className="mt-4 text-sm text-muted-foreground">
                Start with 1 free credit for 1 analysis report now.
            </p>
          </div>
        </div>
      </section>

      <section className="pb-16 sm:pb-20" aria-label="ReddigInsight usage steps">
        <div className="mx-auto max-w-7xl space-y-10 px-4 sm:px-6 lg:px-8">
          {steps.map((step, index) => {
            const Icon = step.icon
            const imageFirst = index % 2 === 1

            return (
              <Card key={step.step} className="overflow-hidden border-border/40 bg-white/90 shadow-lg backdrop-blur dark:bg-gray-900/90">
                <div className={`grid lg:grid-cols-2 ${imageFirst ? 'lg:[&>*:first-child]:order-2' : ''}`}>
                  <div className="p-6 sm:p-10">
                    <div className="flex items-center gap-3">
                      <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-r from-indigo-500 to-purple-500">
                        <Icon className="h-6 w-6 text-white" aria-hidden="true" />
                      </div>
                      <div>
                        <p className="text-sm font-semibold uppercase tracking-wide text-indigo-600">{step.step}</p>
                        <h2 className="text-2xl font-bold leading-tight">{step.title}</h2>
                      </div>
                    </div>
                    <p className="mt-5 leading-relaxed text-muted-foreground">{step.description}</p>
                    <ul className="mt-6 space-y-3">
                      {step.bullets.map((bullet) => (
                        <li key={bullet} className="flex gap-3 text-sm leading-relaxed">
                          <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-indigo-600" aria-hidden="true" />
                          <span>{bullet}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  <figure className="border-t border-border/40 bg-muted/30 p-4 sm:p-6 lg:border-l lg:border-t-0">
                    <div className="overflow-hidden rounded-xl border border-border/60 bg-white shadow-sm">
                      <Image
                        src={step.image}
                        alt={step.imageAlt}
                        width={step.imageWidth}
                        height={step.imageHeight}
                        priority={index === 0}
                        sizes="(min-width: 1024px) 50vw, 100vw"
                        className={step.tall ? 'max-h-[620px] w-full object-cover object-top' : 'w-full object-cover'}
                      />
                    </div>
                    <figcaption className="mt-3 text-center text-sm text-muted-foreground">
                      {step.imageCaption}
                    </figcaption>
                  </figure>
                </div>
              </Card>
            )
          })}
        </div>
      </section>

      <section className="pb-20">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <Card className="border-border/40 bg-white/90 shadow-lg backdrop-blur dark:bg-gray-900/90">
            <CardContent className="p-6 sm:p-10">
              <div className="flex items-center gap-3">
                <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-r from-indigo-500 to-purple-500">
                  <Settings2 className="h-6 w-6 text-white" aria-hidden="true" />
                </div>
                <h2 className="text-2xl font-bold">What to check before starting</h2>
              </div>
              <p className="mt-5 leading-relaxed text-muted-foreground">
                A clear research question produces the most useful report. Confirm that the selected subreddit is
                relevant, the keywords match the language community members actually use, and the time range covers the
                period you want to understand. You can adjust AI-suggested inputs before the analysis begins.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>
    </div>
  )
}
